package tv.avfun.db;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

public class DBOpenHelper extends SQLiteOpenHelper {

	public DBOpenHelper(Context context) {
		super(context, "acfun.db", null, 5);
	}

	@Override
	public void onCreate(SQLiteDatabase db) {
		db.execSQL("CREATE TABLE SEARCHHISTORY (_ID INTEGER PRIMARY KEY AUTOINCREMENT, TITLE VARCHAR(20))");
		db.execSQL("CREATE TABLE USER (_ID INTEGER PRIMARY KEY AUTOINCREMENT,USERID VARCHAR(20), USERNAME VARCHAR(25),AVATAR TEXT,SIGNATURE TEXT,COOKIES TEXT)");
		db.execSQL("CREATE TABLE NFAVORITES (_ID INTEGER PRIMARY KEY AUTOINCREMENT,VIDEOID VARCHAR(40), TITLE VARCHAR(100),TPYE INTEGER,CHANNELID TEXT)");
		db.execSQL("CREATE TABLE NHISTORY (_ID INTEGER PRIMARY KEY AUTOINCREMENT,VIDEOID VARCHAR(40), TITLE VARCHAR(100),TIME VARCHAR(20),TPYE INTEGER,CHANNELID TEXT)");
	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int old, int n) {
		// TODO Auto-generated method stub
		if(old<4){
			db.execSQL("CREATE TABLE USER (_ID INTEGER PRIMARY KEY AUTOINCREMENT,USERID VARCHAR(20), USERNAME VARCHAR(25),AVATAR TEXT,SIGNATURE TEXT,COOKIES TEXT)");
		}
		
		db.execSQL("CREATE TABLE NFAVORITES (_ID INTEGER PRIMARY KEY AUTOINCREMENT,VIDEOID VARCHAR(40), TITLE VARCHAR(100),TPYE INTEGER,CHANNELID TEXT)");
		db.execSQL("CREATE TABLE NHISTORY (_ID INTEGER PRIMARY KEY AUTOINCREMENT,VIDEOID VARCHAR(40), TITLE VARCHAR(100),TIME VARCHAR(20),TPYE INTEGER,CHANNELID TEXT)");

	}
	

}
