package tv.avfun.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class DBOpenHelper extends SQLiteOpenHelper {

	public DBOpenHelper(Context context) {
		super(context, "acfun.db", null, 8);
	}

	@Override
	public void onCreate(SQLiteDatabase db) {
		db.execSQL("CREATE TABLE SEARCHHISTORY (_ID INTEGER PRIMARY KEY AUTOINCREMENT, TITLE VARCHAR(20))");
		db.execSQL("CREATE TABLE USER (_ID INTEGER PRIMARY KEY AUTOINCREMENT,USERID VARCHAR(20), USERNAME VARCHAR(25),AVATAR TEXT,SIGNATURE TEXT,COOKIES TEXT)");
		db.execSQL("CREATE TABLE NFAVORITES (_ID INTEGER PRIMARY KEY AUTOINCREMENT,VIDEOID VARCHAR(40), TITLE VARCHAR(100),TPYE INTEGER,CHANNELID TEXT)");
		db.execSQL("CREATE TABLE NHISTORY (_ID INTEGER PRIMARY KEY AUTOINCREMENT,VIDEOID VARCHAR(40), TITLE VARCHAR(100),TIME VARCHAR(20),TPYE INTEGER,CHANNELID TEXT)");
		db.execSQL("CREATE TABLE DOWNLOADLIST (_ID INTEGER PRIMARY KEY AUTOINCREMENT,AID VARCHAR(40), VID VARCHAR(40), VTYPE VARCHAR(20), LOCALURI VARCHAR, REMOTEURI VARCHAR,TITLE VARCHAR(255), DURATION INTEGER,I INTEGER, MD5 VARCHAR,STATE INTEGER,DOWNLOADID INTEGER,SIZE INTEGER)");
	}

	@Override
	public void onUpgrade(SQLiteDatabase db, int old, int n) {
		
		if(old<4){
			db.execSQL("CREATE TABLE USER (_ID INTEGER PRIMARY KEY AUTOINCREMENT,USERID VARCHAR(20), USERNAME VARCHAR(25),AVATAR TEXT,SIGNATURE TEXT,COOKIES TEXT)");
		}
		if(old<5){
		    db.execSQL("CREATE TABLE NFAVORITES (_ID INTEGER PRIMARY KEY AUTOINCREMENT,VIDEOID VARCHAR(40), TITLE VARCHAR(100),TPYE INTEGER,CHANNELID TEXT)");
		    db.execSQL("CREATE TABLE NHISTORY (_ID INTEGER PRIMARY KEY AUTOINCREMENT,VIDEOID VARCHAR(40), TITLE VARCHAR(100),TIME VARCHAR(20),TPYE INTEGER,CHANNELID TEXT)");
		}
		if(old<6){
		    db.execSQL("CREATE TABLE DOWNLOADLIST (_ID INTEGER PRIMARY KEY AUTOINCREMENT,AID VARCHAR(40), VID VARCHAR(40),LOCALURI VARCHAR, REMOTEURI VARCHAR,TITLE VARCHAR(255), DURATION INTEGER,I INTEGER, MD5 VARCHAR,STATE INTEGER,DOWNLOADID INTEGER)");
		}
		if(old<7){
		    db.execSQL("ALTER TABLE DOWNLOADLIST ADD SIZE INTEGER");
		}
		if(old<8){
		    db.execSQL("ALTER TABLE DOWNLOADLIST ADD VTYPE VARCHER(10)");
		}
	}
	

}
